### PR TITLE
Pass SHELLCHECK_OPTS to docker container

### PR DESCRIPTION
**Pull request by rajbos**
Related to #40

Adds support for passing `SHELLCHECK_OPTS` to the Docker container in the `actionlint` GitHub Action.

- Introduces a new input parameter `shellcheck_opts` in `action.yml` to allow users to specify custom `SHELLCHECK_OPTS`.
- Modifies the `docker run` command to include `-e SHELLCHECK_OPTS="${{ inputs.shellcheck_opts }}"`, ensuring that the `SHELLCHECK_OPTS` environment variable is passed to the Docker container.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/devops-actions/actionlint/issues/40?shareId=33676700-593a-4696-90d8-0c20f4577102).

### CODE REVIEW

**Comment by rajbos** [comment]
@piotrekkr, I just noticed the issue again 🙈 and wanted to at least try to add this. Any change you can check and validate if this works, by calling the action with the config and `uses: devops-actions/actionlint@rajbos/pass-shellcheck-opts`?

I'd like at least a confirmation that it works before releasing it.

**Comment by piotrekkr** [comment]
@rajbos Thanks for working on this. Will try to check it today if possible or tomorrow.

**Comment by piotrekkr** [comment]
@rajbos Seems like it works well. Before using PR version I had this
image
After using adding
```
      - name: Run actionlint
        uses: devops-actions/actionlint@rajbos/pass-shellcheck-opts
        with:
          shellcheck_opts: '-e SC2129'
```
I have this:
image

**Comment by rajbos** [comment]
Whoot! Merging this in then and I'll release a new version. Thanks a lot for testing!

**Pull request merged**
